# Site settings
title: Blog do João
author: João Saragossa
email: joaosaragossa.dev@gmail.com
description: Um blog sobre tudo que me dá na telha.
baseurl: "/qualquer-coisa"
url: "http://joaosaragossa.github.io"
facebook_username: joaopaulo.saragossa
twitter_username: joaosaragossa
github_username:  joaosaragossa
permalink: /:title

# Build settings
markdown: kramdown
header_description: Por que não?