# Site settings
title: Qualquer Coisa
author: João Saragossa
email: joaosaragossa.dev@gmail.com
description: Um blog sobre qualquer coisa. Mesmo
baseurl: "/qualquer-coisa"
url: "http://joaosaragossa.github.io"
facebook_username: joaopaulo.saragossa
twitter_username: joaosaragossa
github_username:  joaosaragossa
permalink: /:title

# Build settings
markdown: kramdown
header_description: Mesmo