# Site settings
title: Blog do João
author: João Saragossa
email: joaosaragossa.dev@gmail.com
description: Um blog sobre tudo que me dá na telha.
baseurl: "/blog"
url: "http://joaosaragossa.github.io"
facebook_username: joaopaulo.saragossa
twitter_username: joaosaragossa
github_username:  joaosaragossa
permalink: /:title

# Build settings
markdown: kramdown
header_description: Por que não?
author_img: "http://joaosaragossa.github.io/joao.jpg"

compress_html:
  clippings: [html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]